services:
  dh_streamlit:
    container_name: dh_streamlit
    hostname: dh_streamlit
    build:
      context: docker/dh_streamlit
    ports:
      - "8501:8501"
      - "10000:10000"

    volumes:  # [host volume directory]:[container volume directory]
      - ./app:/app

